Косарев Егор. Задача 2. Вариант 23. Построение выпуклой оболочки – проход Джарвиса.
learning-process/ppc-2024-threads pull request #107
Opened 2024-04-02 16:43 UTC by EgorKosarevv

Параллельная OpenMP реализация построения выпуклой оболочки методом Джарвиса.

2024-04-09 16:15 UTC, allnes commented on tasks/omp/kosarev_e_jarvis/src/ops_omp.cpp
> +  std::this_thread::sleep_for(30ms);
для чего вы это здесь поставили?

2024-04-09 16:15 UTC, allnes requested changes

2024-04-09 16:15 UTC, allnes commented on tasks/omp/kosarev_e_jarvis/src/ops_omp.cpp
> +  std::this_thread::sleep_for(30ms);
и здесь также?

2024-04-13 11:24 UTC, EgorKosarevv commented on tasks/omp/kosarev_e_jarvis/src/ops_omp.cpp
> +  std::this_thread::sleep_for(30ms);
хотел замедлить тесты, чтобы они проходили, но сейчас понял, что в этом надобности нет. Исправил.

2024-04-13 11:24 UTC, EgorKosarevv commented on tasks/omp/kosarev_e_jarvis/src/ops_omp.cpp
> +  std::this_thread::sleep_for(30ms);
хотел замедлить тесты, чтобы они проходили, но сейчас понял, что в этом надобности нет. Исправил.

2024-05-07 15:40 UTC, merged